POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Some blog",
    "author": "Roope Ankka",
    "url": "http://osoiteontama.fi",
    "likes": 2,
    "userId": "655da96a9ae6e5a847deabdc"
}